### ISSUE TITLE
Support process types in heroku.yml

### ISSUE THREAD

**Issue by jkutner** [heroku/plugin-container-build#20]
The `push` command should detect and support process types in the `heroku.yml`. For example:

```yaml
run:
  web: start.sh
  worker: worker.sh
```

This dependent on determining the order of precedence for `Procfile` and `heroku.yml`.
